### ISSUE TITLE
Using HTTPS - key/cert file

### ISSUE THREAD

**Issue by asheroto** [warren-bank/HLS-Proxy#13]
Hi there,

First off - thanks so much for this project! It comes in very handy! 👍💯

Can you kindly provide an example of how to pass a key/cert for HTTPS?

I need to use `--req-options` and give it a filename of a JS file that modifies the `options` object, right?

I'm trying...

```
--tls --host "myhost.hostname.com:443" --port "3005" --req-options "/path/to/the/file/options.js"
```

And in options.js I have...

```
var options = {
  key: fs.readFileSync('/path/to/privkey.pem'),
  cert: fs.readFileSync('/path/to/cert.pem')
};
```

I think I missing something though, as this does not work?

Thank you very much. :-)

**Comment by asheroto** [comment]
I ended up just symlinking the certs in `hls-proxy/servers/cert` but am curious if this can be done anyhow? :-)

**Comment by warren-bank** [comment]
sorry for the delay.. I was focused on a different project.. bad timing to come up for air.

anyway.. I had to take a peek at the code to answer your question.. and the answer is: I never exposed any cli options to customize the path to certificate files.

strictly speaking.. I should probably add: `--tls-key` `--tls-cert` and (an optional) `--tls-pass`

but, given the current coding.. what you did is fine; the other workaround would be to manually update the code [here](https://github.com/warren-bank/HLS-Proxy/blob/v0.18.3/hls-proxy/servers/start_https.js#L14).. and hard-code your own paths.

PS: `--req-options` aren't used to configure the proxy server.. these values are used to configure the HTTP requests that are made to the video server(s)

**Comment by asheroto** [comment]
Awesome, thanks for the info!
