### ISSUE TITLE
Content for Youtube live m3u8 does not pass thru HLS-Proxy

### ISSUE THREAD

**Issue by yomomano** [warren-bank/HLS-Proxy#19]
I seen several similar issues reported and tried all the answers but nothing seems to work, so here the following:

I am trying to stream a live Youtube channel and managed to fetch the m3u8 URL for it, and created a HLS-Proxy URL for it like this:

```bash
proxy_url='http://localhost:8081'
video_url='https://manifest.googlevideo.com/api/.....some very long url..---.QFbPavapnNEKuwk61I%3D/file/index.m3u8'
file_extension='.m3u8'
hls_proxy_url="${proxy_url}/"$(echo -n "$video_url" | base64 --wrap=0)"$file_extension"
```

This URL plays well in VLC for example but not Clappr. 

When I use it as a `src` for a HTML5 video element using `NPM hls.js` library, the content remains pointing to Youtube (googlevideo). Here is how I create/assign the video src:

```javascript
      if (Hls.isSupported()) {
        var hls = new Hls();
        hls.loadSource(videoSrc); // HLS-Proxy like http://localhost:8081/....
        hls.attachMedia(videodom); // HTML5 video
      }
```

Once it starts playing, the outgoing connections all point to googlevideo, and I get a CORS error.

What am I doing wrong?  I was assuming the content is all going thru the proxy by default. Or is hls.js to blaim?

Server start command:

```npm start -- --port "8081" --host "localhost" --prefetch --max-segments 10 -v 4```

- output attached-

Curl response YT URL `https://manifest.googlevideo.com/api/manifest/hls_variant/....`

```
curl -I "$hls_proxy_url"

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Headers: *
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 86400
Content-Type: application/x-mpegURL

Connection: keep-alive
Keep-Alive: timeout=5
```

Also attached the master m3u8 for reference.

Thank you! Great project and documentation ! Perfect to learn the game.

[SkyNewsLive-index.zip](https://github.com/warren-bank/HLS-Proxy/files/9920145/SkyNewsLive-index.zip)

[out.log](https://github.com/warren-bank/HLS-Proxy/files/9920705/out.log)

**Comment by warren-bank** [comment]
hls.js should (almost certainly) work.. but I haven't tried.. so dunno.

clappr most definitely works.. I just tested it; of course, the IP:port of my local proxy is probably going to be different from yours.. so adjust the URLs as needed.

**Comment by yomomano** [comment]
Everything is working fine via hls.js and HTML5 video. I even get the expected events like 'loadedmetadata', 'canplay' etc. Perfect.

Thanks Warren for this great tool !
