### ISSUE TITLE
Fails to modify m3u8 content when server doesn't response with a "content-encoding" header

### ISSUE THREAD

**Issue by Shepless** [warren-bank/HLS-Proxy#26]
Firstly, thanks for such an excellent package and all the work you have put into this @warren-bank 

After spending some time (and failing!) to get my my m3u8 file to proxy correctly, I spent some time debugging it and found that if a response doesn't include a `content-encoding` header the response just returns empty, This empty response then stops the `modify_m3u8_content` function from modifying the contents to prepend the proxied URL.

I was hoping to fix it myself, but alas my node stream skills aren't very good so I have spent a few hours failing.

The issue isn't your library really, just poorly implemented server responses. But the issue occurs [here](https://github.com/warren-bank/node-request/blob/master/lib/zlib_utils.js#L26) in your request package

**Update**
Things I tried when fixing myself:
- if the response has no content-encoding, return `data.toString('utf-8')`. This however just resulted in the data printing `[object Object]`
- Creating a transform stream as an decoder (default in the case statement if the content-encoding is emtpy). But this just seemed to output the Transform stream object when attempting to get the data out

**Comment by warren-bank** [comment]
the line of code you point to is:
```js
if ((data instanceof Object) && (data.headers instanceof Object) && (typeof data.headers['content-encoding'] === 'string')){
  // ...
  return decoded_data
}
return data
```

is the issue that the server is returning the header:
```text
content-encoding: 
```

so it exists.. it's a string.. but it has an empty value?

if so, would simply changing that line to also test that the value is non-empty fix your issue?

```js
if ((data instanceof Object) && (data.headers instanceof Object) && (typeof data.headers['content-encoding'] === 'string') && data.headers['content-encoding']){
  // ...
  return decoded_data
}
return data
```

**Comment by Shepless** [comment]
@warren-bank I shall give that a try. However, I forgot that whilst debugging I found that it wasn't hitting the modify m3u8 content function at all because the m3u8 I'm using has .ts extensions for each stream. For example:

```
#EXTINF:
aHR0cHM6Ly90dm5vdy5iZXN.....=.ts
```

This makes it skip due to the is_m3u8 check in the proxy.js. I forgot when debugging that I had forced it to modify the content when I stumbled on the content-encoding issue.

**Comment by warren-bank** [comment]
sorry.. I answered before actually reading what was inside of that `if` block..

now, I see that the value of the header is tested for supported encodings..
and if the value isn't supported (or is empty)..
then the decoder doesn't do anything..
so the method is harmless

**Comment by warren-bank** [comment]
can we just start at the beginning..
you can change the URL domains and paths..
but just give an idea of what you've done..
so I can quickly confirm that it isn't something simple and obvious.

what does the URL for the manifest look like..
that you are giving to a client..
for it to access a stream via the proxy?

`http://<ip of proxy>:<port of proxy>/<base64 of manifest URL>.m3u8`

**Comment by Shepless** [comment]
Sorry, that is my fault for confusing this. So from start to finish:

I have base64'd my URL and passed that to the proxy: `http://127.0.0.1/`. I get the following output (shortened for brevity):

```
#EXTM3U
#EXTINF:-1 tvg-id="5.star.max.eastern.us" tvg-name="5.star.max.eastern.us" tvg-type="live" group-title="US" tvg-logo="https://media.tv4.live/5.star.max.eastern.us.png",5 Star Max (East)
http://127.0.0.1:9002/aHR0cHM6Ly90dm5vdy5iZXN0L2FwaS9zdHJlYW0vc2VyaW91c3BpZzEzQG91dGxvb2suY29tLzJVYzk3VVk2S0RTa0hmZzY5eWttQUNCb201L2xpdmV0di5lcGcvNS5zdGFyLm1heC5lYXN0ZXJuLnVzLm0zdTg=.ts
#EXTINF:-1 tvg-id="ae.us.eastern.us" tvg-name="ae.us.eastern.us" tvg-type="live" group-title="US" tvg-logo="https://media.tv4.live/ae.us.eastern.us.png",A&E (East) US
http://127.0.0.1:9002/aHR0cHM6Ly90dm5vdy5iZXN0L2FwaS9zdHJlYW0vc2VyaW91c3BpZzEzQG91dGxvb2suY29tLzJVYzk3VVk2S0RTa0hmZzY5eWttQUNCb201L2xpdmV0di5lcGcvYWUudXMuZWFzdGVybi51cy5tM3U4.ts
etc etc etc
```
When I try and play one of those stream URLs (notice the .ts extension). Then it errors because when it gets chunks it is just passing the raw data of `/12345.ts` through the proxy.

I found that there are two things issues:

- The .ts extension cuts the proxy middleware short as it fails the `is_m3u8` check. When debugging (as a test) I forced this through by doing the following:

```
if (!is_m3u8) {
        response.pipe(res);
        
        // FORCE IT TO MODIFY (AS A TEST)
        const m3u8_url = (redirects && Array.isArray(redirects) && redirects.length)
          ? redirects[(redirects.length - 1)]
          : url
        res.writeHead(200, { "Content-Type": "application/x-mpegURL" })
        res.end( modify_m3u8_content(response.toString().trim(), m3u8_url, referer_url, redirected_base_url) )
}
```

This then led me to the second issue where the url being request for the stream chunks isn't returning a `content-encoding` header. If there is no content encoding set then calling `data.toString('urf-8')` returns `[object Object]`

I hope that helps clear things up. Sorry for the initial confusion

**Comment by warren-bank** [comment]
that manifest isn't HLS..

IPTV .m3u lists of channels look a lot like HLS .m3u8 lists of video chunks..
it's confusing..
but your manifest is for IPTV, and each `.ts` URL points to a stream..
whereas in HLS, each `.ts` URL points to a file that holds about 10 seconds of video.

I don't really know the technical specifics..
only that the distinction is a constant source of aggrevation.

**Comment by Shepless** [comment]
I thought that at first too, but under the hood it is an m3u8, the .ts is doing a 301 redirect to the m3u8 (annoyingly!) I added this console log in to debug it inside the request module:

```js
const redirect = resolveRedirectLocation(error.location, original_url, redirects)
console.log('REDIRECT DETECTED FROM', original_url, 'TO', redirect);
```

Example Output:
```
REDIRECT DETECTED
FROM
https://tvnow.best/api/stream/xxx/xxxx/livetv.epg/5.star.max.eastern.us.m3u8
TO
https://195-181-172-33.servers.tips:5052/live11/Otr8WWXE98TJUfn97yfsIQ/632263/1679019690/1022584.m3u8
```

curl -i https://195-181-172-33.servers.tips:5052/live11/Otr8WWXE98TJUfn97yfsIQ/632263/1679019690/1022584.m3u8
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 16 Mar 2023 22:24:36 GMT
Content-Type: application/vnd.apple.mpegurl
Content-Length: 252
Connection: keep-alive
Last-Modified: Thu, 16 Mar 2023 22:24:25 GMT
ETag: "64139719-fc"
Expires: Thu, 16 Mar 2023 22:24:41 GMT
Cache-Control: max-age=5
Strict-Transport-Security: max-age=31536000; includeSubdomains;
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
Access-Control-Expose-Headers: Content-Length,Content-Range

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#EXT-X-MEDIA-SEQUENCE:2640
#EXTINF:11.878533,
1022584_2640.ts
#EXTINF:11.177833,
1022584_2641.ts
#EXTINF:12.212200,
1022584_2642.ts
#EXTINF:12.679333,
1022584_2643.ts
#EXTINF:12.645967,
1022584_2644.ts
```

**Comment by warren-bank** [comment]
i'm lost..
you said URLs with a .ts extension are redirecting to URLs with a .m3u8 extension..
but your example is .m3u8 to .m3u8

where did this come from:
`https://tvnow.best/api/stream/xxx/xxxx/livetv.epg/5.star.max.eastern.us.m3u8`

**Comment by warren-bank** [comment]
and..
presumably..
having cherry picked the URL for an HLS manifest for only one channel.. 
will it work with the proxy (if used directly)?

**Comment by Shepless** [comment]
Source m3u8 contents:

```
#EXTM3U
#EXTINF:-1 tvg-id="5.star.max.eastern.us" tvg-name="5.star.max.eastern.us" tvg-type="live" group-title="US" tvg-logo="https://media.tv4.live/5.star.max.eastern.us.png",5 Star Max (East)
https://tvnow.best/api/stream/<user>/<password>/livetv.epg/5.star.max.eastern.us.m3u8
```
When your proxy parses this (by giving it the base64 URL) it generates this with .ts exentions.

```
#EXTM3U
#EXTINF:-1 tvg-id="5.star.max.eastern.us" tvg-name="5.star.max.eastern.us" tvg-type="live" group-title="US" tvg-logo="https://media.tv4.live/5.star.max.eastern.us.png",5 Star Max (East)
http://127.0.0.1:9002/aHR0cHM6Ly90dm5vdy5iZXN0L2FwaS9zdHJlYW0vc2VyaW91c3BpZzEzQG91dGxvb2suY29tLzJVYzk3VVk2S0RTa0hmZzY5eWttQUNCb201L2xpdmV0di5lcGcvNS5zdGFyLm1heC5lYXN0ZXJuLnVzLm0zdTg=.ts
```

I don't know why it's doing that, but the url above in the source m3u8 does a 301 redirect to: https://195-181-172-33.servers.tips:5052/live3/NxFSsJ5_phESF_BSD0-hgQ/632263/1679020894/24005968.m3u8 (so I would have assumed this is what would be in the generated proxy m3u, not the .ts stuff?)

**Comment by Shepless** [comment]
> and.. presumably.. having cherry picked the URL for an HLS manifest for only one channel.. will it work with the proxy (if used directly)?

If I cherry pick one of this streams to proxy directly, it still fails because it isn't rewriting the m3u file contents, its just using the raw output for the chunks (/12345.ts)

**Comment by warren-bank** [comment]
ok.. I see the problem

you're feeding an EPG into the proxy in place of a manifest.
because the manifest doesn't have the tags that the parser uses to identify it as being a `master` manifest,
it is seen as being a video manifest..
and all URLs in a video manifest are for video segments (ie: .ts files)

try this..
forget about the EPG..
cherry pick one channel (ex: `5 Star Max (East)`)..
and try to proxy the URL for its HLS manifest (ex: `https://tvnow.best/api/stream/<user>/<password>/livetv.epg/5.star.max.eastern.us.m3u8`)

what happens?

**Comment by Shepless** [comment]
Sorry, I had just tried that before you replied. See the above response. Apologies (and thank for all your help with this!)

![Screenshot from 2023-03-16 22-51-04](https://user-images.githubusercontent.com/3731526/225770069-c33205f1-a309-4b32-a0db-84d2197d5ab8.png)

If i play the non-proxy url this is what happens:
![Screenshot from 2023-03-16 22-52-44](https://user-images.githubusercontent.com/3731526/225770272-190af840-1847-4d8a-87d0-5d26efc28eb9.png)

![Screenshot from 2023-03-16 22-52-52](https://user-images.githubusercontent.com/3731526/225770280-a178845d-ea3c-49a5-98fe-06e070787b3a.png)


![Screenshot from 2023-03-16 22-54-02](https://user-images.githubusercontent.com/3731526/225770448-c882c394-33a1-49e6-bc77-4160ec13da38.png)


So it looks like the 301 redirect is affecting it somehow.

**Comment by warren-bank** [comment]
I think you misunderstood..
because your example that failed is still using a .ts extension..
which it shouldn't be

what I'm saying is..
use that URL (for the particular channel)..
as your starting point to proxy..
and it should work

**Comment by Shepless** [comment]
I did just that. (used the base64 encoded string for `https://tvnow.best/api/stream/<user>/<password>/livetv.epg/5.star.max.eastern.us.m3u8`)

That first screen shot is when it tried to request chunks from the proxy. Here it is with more context.

![Screenshot from 2023-03-16 22-58-32](https://user-images.githubusercontent.com/3731526/225770965-a1f551f2-a783-4a8c-bf39-8c4d99ad4a91.png)

the .ts chunks are 404ing because the proxy isn't modifying the m3u8 content to prepend the base64 hash. My guess is because `https://tvnow.best/api/stream/<user>/<password>/livetv.epg/5.star.max.eastern.us.m3u8` does a 301 redirect to `https://195-181-172-33.servers.tips:5052/live3/KJM_52qoazU4umeRv8Fhag/632263/1679022183/24005968.m3u8`?

**Comment by warren-bank** [comment]
humor me..

1. go here: [http://webcast-reloaded.surge.sh/proxy.html](http://webcast-reloaded.surge.sh/proxy.html)
2. enter: [https://tvnow.best/api/stream/<user>/<password>/livetv.epg/5.star.max.eastern.us.m3u8](https://tvnow.best/api/stream/<user>/<password>/livetv.epg/5.star.max.eastern.us.m3u8)
3. configure for: `127.0.0.1:9002`
4. choose the `Clappr` video player, and watch the stream in your browser
   - you can inspect both the `Network` tab in Chrome devtools, and the command-line logs from your proxy
   - but I'm guessing it'll just work

**Comment by Shepless** [comment]
I don't get an option for clappr, unless im doing something wrong.

![Screenshot from 2023-03-16 23-06-09](https://user-images.githubusercontent.com/3731526/225771948-8ce96969-0c48-4658-978d-361af4a7f7ed.png)

**Comment by warren-bank** [comment]
sorry, "Clappr" is under "Chromecast sender"

**Comment by warren-bank** [comment]
choosing "HLS-Proxy configuration" is the page that I sent you to directly..
choosing it from the dropdown just loops you back in a circle

**Comment by Shepless** [comment]
Aye sorry, got there in the end. I get CORS errors, guessing thats my proxy setup?

**Comment by warren-bank** [comment]
that should never happen with the proxy.. it always adds CORS headers

**Comment by Shepless** [comment]
![Screenshot from 2023-03-16 23-10-26](https://user-images.githubusercontent.com/3731526/225772426-8ecb2801-0dff-4609-8773-451dbdc6d82d.png)

**Comment by Shepless** [comment]
If this is any help:
![Screenshot from 2023-03-16 23-12-08](https://user-images.githubusercontent.com/3731526/225772669-9dc1758e-5188-4dee-9dc0-358c8466c5b4.png)

**Comment by warren-bank** [comment]
that's specific to your browser and its security policy..
and that changes with every release..

you need a browser that can load an HTTP (not secure) page..
run a script from an HTTPS (secure) URL..
and XHR content from HTTP at localhost.

**Comment by warren-bank** [comment]
if you want..
you can run the proxy with https..
and load the same proxy page from [here](https://warren-bank.github.io/crx-webcast-reloaded/external_website/proxy.html) with https

**Comment by warren-bank** [comment]
otherwise, you'll need to figure out what options to change.. or flags to pass to the browser when you start it (from the command line)

**Comment by Shepless** [comment]
ok got it working. but its getting lots of 500 errors
![Screenshot from 2023-03-16 23-17-45](https://user-images.githubusercontent.com/3731526/225773315-288c5331-389c-44f2-b25a-08cf4a326cdd.png)

Im guessing you got logs on that?

**Comment by warren-bank** [comment]
don't look at me..

```text
view-source:http://webcast-reloaded.surge.sh/4-clappr/index.html
```

shows that Clappr is coming from:
```text
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr@0.3.13/dist/clappr.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/level-selector@0.2.0/dist/level-selector.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr-chromecast-plugin@0.1.1/dist/clappr-chromecast-plugin.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/dash-shaka-playback@3.0.3/dist/dash-shaka-playback.min.js"></script>
```

..that's a pretty standard CDN

**Comment by Shepless** [comment]
But those 500s are coming from the local proxy?

![Screenshot from 2023-03-16 23-23-06](https://user-images.githubusercontent.com/3731526/225773965-7e876593-86f4-4aef-acc6-58d87ac907ae.png)

**Comment by warren-bank** [comment]
oh yeah, sorry.. you're right.. the XHR request was made by Clappr (which did load).. and that's what's hitting browser security blocks

anway.. this is getting way off track

* click "Back"
* choose "ExoPlayer Sender" from the dropdown
* copy the URL from the text field
* play in VLC (or similar)

**Comment by warren-bank** [comment]
sorry: "AirPlay sender"

**Comment by Shepless** [comment]
That works fine in VLC.

**Comment by warren-bank** [comment]
yeah, no browser security to mess things up

**Comment by Shepless** [comment]
So the conclusion is - it works :rofl: ? Was the issue with me trying it a web based player? (Aside from the M3U beng a TVG format - which I can sort my end)

**Comment by warren-bank** [comment]
that was supposed to be the fast way to test what I was saying..
but boy, did that go off track..
anyway.. it proves that:

1. if you cherry pick the URL for one channel from your EPG guide.. you can use it with HLS Proxy
2. if you want to play a stream from HLS-Proxy in your browser.. you need to configure your browser to allow it

as I said earlier.. your screenshot that you said failed shows you trying to proxy a manifest with a .ts extension.. which made no sense. this little test proved that you can proxy an .m3u8 extension URL.. taken from within your EPG.

**Comment by warren-bank** [comment]
..but __NOT__ the .m3u8 URL for the EPG itself!!

..because it isn't an HLS manifest

**Comment by Shepless** [comment]
Oh man, I'm so sorry! I really appreciate your effort and patience with me on this! I've learnt a lot. Thanks again. I'll close this behemoth off.

**Comment by warren-bank** [comment]
no worries.. glad you find the proxy useful :)
