### ISSUE TITLE
Run proxy from a subfolder

### ISSUE THREAD

**Issue by wimme** [warren-bank/HLS-Proxy#37]
I would like to use this proxy on an existing website. I'm not allowed to open additional ports. So I was thinking to proxy incoming requests via our webserver to this HLS proxy. This seems to be possible by specifying the host and port in the `--host` option (as said [here](https://github.com/warren-bank/HLS-Proxy/issues/11#issuecomment-995446952)).

As I want to offer the website and the HLS proxy on the same host:port, I would need to run this HLS proxy from a sub folder.

```
https://host:443/proxy/* --> webserver --> HLS proxy on port 8080
https://host:443/* --> webserver --> website
```

Is this possible?

**Comment by warren-bank** [comment]
1. if your current web server happens to use Node.js with Express.js
   - then _HLS-Proxy_ can be used as standard middleware.. at any route you like
   - [examples](https://github.com/warren-bank/HLS-Proxy/tree/v03/.recipes/03.%20Express.js%20app%20with%20custom%20route)
2. otherwise, what you suggest is perfectly doable
   - of course, your current web server will need the ability to intercept and conditionally reverse proxy requests
   - this functionality could either be:
     * directly supported by the web server
       - for example, my [modifications to _serve_](https://github.com/warren-bank/node-serve) make this possible off-the-shelf
     * implemented by a plugin or module that the web server does support
       - for example: Apache supports [_mod_proxy_](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html) that should make this [simple to configure](https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html)
     *  implemented by a cgi-script in a language that the web server does support
        - for example: PHP, perl, ...

**Comment by wimme** [comment]
It's indeed possible to do conditionally reverse proxy requests on the web server (we have this already working on Windows IIS). But will *HLS-Proxy* be able to correctly rewrite the urls in the m3u8 file to include the sub folder? Is this configurable? Because internally it runs on port 8080 (for example) without a sub folder.
Additional question, can the web server also handle the HTTPS encryption? Will `--host "mydomain.com:443"` output the urls in the m3u8 as HTTPS?

**Comment by warren-bank** [comment]
1. start _HLS Proxy_ behind the firewall on an unused/unprotected port (ex: 8080)
   ```bash
     hlsd -v 3 --host "serve.local:80" --port 8080
   ```
2. configure the web server that hosts `serve.local:80` to reverse proxy a particular custom route
   ```bash
     NO_UPDATE_CHECK='1'

     serve --config 'serve.json' --cors --listen 'tcp:0.0.0.0:80'
   ```
   * example: [_serve.json_](https://github.com/warren-bank/node-serve/tree/master/lib/serve#configuration) config file
     ```text
       {
         "renderSingle":  false,
         "cleanUrls":     false,
         "trailingSlash": false,
         "etag":          false,
         "symlinks":      false,
         "logReq":        true,
         "logRes":        true,

         "redirects": [
           {
             "engine":        "regex",
             "source":        "^/(hls-proxy/.+)$",
             "destination":   "http://localhost:8080/$1",
             "flags":         "",
             "decode":        false,
             "terminal":      true,
             "preserveQuery": false,
             "preserveHash":  false,
             "proxy":         true
           }
         ]
       }
     ```
   * extra example: Apache _.htaccess_ file
     ```text
       RewriteEngine On

       RewriteRule "^/?(hls-proxy/.+)$" "http://localhost:8080/$1" [P,L]
     ```
3. test:
   ```bash
     video_url='https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8'
     curl -s --insecure "$video_url"

     video_url=$(echo -n "$video_url" | base64 --wrap=0)'.m3u8'
     video_url="http://serve.local/hls-proxy/${video_url}"
     # http://serve.local/hls-proxy/aHR0cHM6Ly9kZW1vLnVuaWZpZWQtc3RyZWFtaW5nLmNvbS9rOHMvZmVhdHVyZXMvc3RhYmxlL3ZpZGVvL3RlYXJzLW9mLXN0ZWVsL3RlYXJzLW9mLXN0ZWVsLmlzbS8ubTN1OA==.m3u8
     curl -s "$video_url"
   ```
4. [watch video](http://webcast-reloaded.surge.sh/4-clappr/index.html?override=true#/watch/aHR0cDovL3NlcnZlLmxvY2FsL2hscy1wcm94eS9hSFIwY0hNNkx5OWtaVzF2TG5WdWFXWnBaV1F0YzNSeVpXRnRhVzVuTG1OdmJTOXJPSE12Wm1WaGRIVnlaWE12YzNSaFlteGxMM1pwWkdWdkwzUmxZWEp6TFc5bUxYTjBaV1ZzTDNSbFlYSnpMVzltTFhOMFpXVnNMbWx6YlM4dWJUTjFPQT09Lm0zdTg%253D) in browser

notes:
* I just tested the above configs and it works perfectly
  - my `hosts` file includes the line:<br>`127.0.0.1 serve.local`
  - the test video played in my browser
  - all requests were reverse proxied by `serve` and handled by `HLS Proxy`
* at some point, I did major rewrites
  - presumably when I added better support for use with _Express.js_
  - in doing so, any leading path in the request is echoed into all proxied URLs in the modified manifest<br>for example:
    * request: `http://localhost:8080/hls-proxy/12345.m3u8`
      - leading path = `/hls-proxy/`
      - base64 encoded video URL = `12345`
      - file type: `m3u8`
  - relevant code: [1](https://github.com/warren-bank/HLS-Proxy/blob/v3.4.0/hls-proxy/proxy.js#L43), [2](https://github.com/warren-bank/HLS-Proxy/blob/v3.4.0/hls-proxy/utils.js#L19), [3](https://github.com/warren-bank/HLS-Proxy/blob/v3.4.0/hls-proxy/manifest_parser.js#L126), [4](https://github.com/warren-bank/HLS-Proxy/blob/v3.4.0/hls-proxy/manifest_parser.js#L333), [5](https://github.com/warren-bank/HLS-Proxy/blob/v3.4.0/hls-proxy/manifest_parser.js#L351)

**Comment by wimme** [comment]
Thanks for all the info. I created the following reverse proxy rule on the web server:

```
https://host/hls-proxy/(.*) --> webserver --> http://hlsproxy:8080/hls-proxy/{R:1}
```

What I was missing was that I had to put the subfolder in the *HLS proxy* URL.
I can confirm, the leading path in the request gets echoed back, so running it from a sub folder seems to work fine!

The remaining issue I have is to handle the HTTPS encryption on the front-end web server.

Requesting url: https://host/hls-proxy/aHR0cHM6Ly90ZXN0LXN0cmVhbXMubXV4LmRldi94MzZ4aHp6L3gzNnhoenoubTN1OA==.m3u8

This results in:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2149280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=1280x720,NAME="720"
http://host:80/hls-proxy/aHR0cHM6Ly90ZXN0LXN0cmVhbXMubXV4LmRldi94MzZ4aHp6L3VybF8wLzE5MzAzOTE5OV9tcDRfaDI2NF9hYWNfaGRfNy5tM3U4.m3u8
...
```

I can't auto-redirect it to HTTPS because the website uses HTTPS, so it gets blocked in the browser: "*Mixed Content: The page at '&lt;URL&gt;' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '&lt;URL&gt;'. This request has been blocked; the content must be served over HTTPS.*"

I can probably workaround this by configuring the certificates in the *HLS proxy* directly, although it's not ideal.

**Comment by warren-bank** [comment]
hmm.. good point.

as you say, it isn't ideal.. but it would work to:

1. run an instance of _HLS Proxy_ to service public port 80:
   ```bash
     hlsd -v 3 --host "serve.local:80" --port 8080
   ```
2. run another instance of _HLS Proxy_ to service public port 443:
   ```bash
     hlsd -v 3 --tls --host "serve.local:443" --port 8081
   ```
3. add a reverse proxy rule for each:
   ```text
     http://host:80/hls-proxy/(.*)   --> webserver --> http://localhost:8080/hls-proxy/{R:1}
     https://host:443/hls-proxy/(.*) --> webserver --> https://localhost:8081/hls-proxy/{R:1}
   ```

- - - -

alternatively, maybe I should:
* set the public facing protocol to "https" when --host ends with ":443"
* regardless of whether the hls-proxy is started with --tls

In which case:

1. run an instance of _HLS Proxy_ to service public port 443:
   ```bash
     hlsd -v 3 --host "serve.local:443" --port 8080
   ```
2. add a single reverse proxy rule:
   ```text
     https://host:443/hls-proxy/(.*) --> webserver --> http://localhost:8080/hls-proxy/{R:1}
   ```

I can't imagine this easter-egg of an exception biting anybody unexpectedly.
Thoughts?

**Comment by warren-bank** [comment]
note (to self)..

the touchpoint for making this change is [here](https://github.com/warren-bank/HLS-Proxy/blob/v3.4.0/hls-proxy/utils.js#L27)

for example:
```javascript
  result.redirected_base_url = `${ (is_secure || (host && host.endsWith(':443'))) ? 'https' : 'http' }://${host || req.headers.host}${expressjs.get_base_req_url(req) || matches[1] || ''}`
```

**Comment by warren-bank** [comment]
[v3.4.1](https://github.com/warren-bank/HLS-Proxy/commit/decbb93aac2a881366160f7a83f8064e09491a50) adds that change..
it's already available on npm

**Comment by wimme** [comment]
Awesome, this is great. Tested and deployed, works perfect. Thanks, very much appreciate your effort on this.
