### ISSUE TITLE
How can I deploy this on railway.app?

### ISSUE THREAD

**Issue by amamadman** [warren-bank/HLS-Proxy#46]

**Comment by warren-bank** [comment]
Have you tried?

Based on reading [_The Basics: Services_](https://docs.railway.app/overview/the-basics#services) and [_Deployments: Start Command_](https://docs.railway.app/guides/start-command), it would seem that deployment involves simply telling them the URL for a public git repo (for [example](https://github.com/warren-bank/HLS-Proxy.git)) and their platform should do the rest: recoginize that it's a Node.js app, provision the correct runtime, obtain the start command from `package.json`.

Based on reading [_Pricing_](https://railway.app/pricing), it would cost $0.10/GB of data sent from proxy to user; not clear whether there's any cost for the data between proxy and origin server. On the upside for testing, anyone can sign up for a free account without providing any credit card info.. and get $5 of credit to kick the tires.

**Comment by warren-bank** [comment]
I can tell you that I have deployed this server on [Render.com](https://render.com/)..
it works great and [the process](https://github.com/warren-bank/render-web-services/tree/hls-proxy) couldn't be any easier.

Also, their [free tier](https://render.com/pricing) includes (among _many_ other things) 100GB of exit bandwidth per month, and all inbound bandwidth is free. So, for comparison, the same 100GB would cost you $15/month at railway ($5 for a "hobby" plan and $10 for the monthly bandwidth).

**Comment by amamadman** [comment]
> I can tell you that I have deployed this server on [Render.com](https://render.com/).. it works great and [the process](https://github.com/warren-bank/render-web-services/tree/hls-proxy) couldn't be any easier.
> 
> Also, their [free tier](https://render.com/pricing) includes (among _many_ other things) 100GB of exit bandwidth per month, and all inbound bandwidth is free. So, for comparison, the same 100GB would cost you $15/month at railway ($5 for a "hobby" plan and $10 for the monthly bandwidth).

How do I deploy to render then? Can you make a template? Thank you so much for your reply!

**Comment by amamadman** [comment]
Thank You so much!
