### ISSUE TITLE
Dedicated bandwidth downstream to improve player experience

### ISSUE THREAD

**Issue by hblanken** [warren-bank/HLS-Proxy#5]
Warren - Thank you for the code and detailed readme. I am briefly exploring proxies and wanted to ask whether this repository addresses what I am looking for:
I am pushing adaptive .ts chunks to a browser via cdn.
I want to further improve the player experience through dedicating bandwidth to the downstream connection from server to client player. I.e. less drop outs, less buffering.
Especially with multiple parallel .ts streams.
Will this proxy help?

**Comment by warren-bank** [comment]
Off-hand, I'd say no.

My reasoning includes:
* any centralized proxy would lose the advantage of using a globally distributed CDN
* this tool was never intended for a high-scale multi-user environment
  - the caching mechanism isn't designed for it, and would need to be disabled
  - while there is the ability to control how many parallel downloads are used to prefetch .ts chunks, there is no support for controlling or dedicating bandwidth to client connections

**Comment by hblanken** [comment]
thanks @warren-bank very helpful.
