### ISSUE TITLE
Cant proxy

### ISSUE THREAD

**Issue by Brijendrasial** [warren-bank/HLS-Proxy#52]
curl -I --referer https://tvcanale.live/ https://hzt.mizhls.ru/hzt/protv/tracks-v1a1/mono.m3u8

**Comment by warren-bank** [comment]
2 thoughts:

1. I'm not your tech support
   * if you can't figure out how to do something generic..<br>that doesn't directly have to do with this app,<br>please ask on stackoverflow.. not here
2. the `referer` option for `curl` takes a value

**Comment by warren-bank** [comment]
I'll take a quick peek..

1. `curl` shows a _200 OK_ response
2. running my _hls-proxy_ at `192.168.0.2`, [this](http://webcast-reloaded.surge.sh/index.html#/watch/aHR0cDovLzE5Mi4xNjguMC4yOjgwODAvYUhSMGNITTZMeTlvZW5RdWJXbDZhR3h6TG5KMUwyaDZkQzl3Y205MGRpOTBjbUZqYTNNdGRqRmhNUzl0YjI1dkxtMHpkVGg4YUhSMGNITTZMeTkwZG1OaGJtRnNaUzVzYVhabEx3PT0ubTN1OA==) works fine for me
   - the stream played well in [_Clappr_](http://webcast-reloaded.surge.sh/4-clappr/index.html?override=true#/watch/aHR0cDovLzE5Mi4xNjguMC4yOjgwODAvYUhSMGNITTZMeTlvZW5RdWJXbDZhR3h6TG5KMUwyaDZkQzl3Y205MGRpOTBjbUZqYTNNdGRqRmhNUzl0YjI1dkxtMHpkVGg4YUhSMGNITTZMeTkwZG1OaGJtRnNaUzVzYVhabEx3PT0ubTN1OA==)
   - the script to start my _hls-proxy_ includes the following options:
     ```bash
       hlsd --port 8080 -v 1 --req-insecure --copy-req-headers
     ```

**Comment by Brijendrasial** [comment]
Hello,

The question was regarding hlsproxy only but I think I didnt explain it well. I just gave you example of running it with referer. how can I run it with binding with domain name?

**Comment by Brijendrasial** [comment]
I tried every possibility but I am getting 403.

**Comment by Brijendrasial** [comment]
actually the main issue is for me curl itself showing 403 so I cant proxy it with hls.
