### ISSUE TITLE
Rotating proxy or multiple proxy

### ISSUE THREAD

**Issue by Brijendrasial** [warren-bank/HLS-Proxy#54]
Hello Warren,

Any plan to add multiple proxies or rotating proxies?

**Comment by warren-bank** [comment]
no, but you could always use a proxy load balancer (such as [this](https://github.com/kpcyrd/laundry5)).

**Comment by Brijendrasial** [comment]
Looks like it supports socks5 proxy list. Any other solution that supports http proxy?

**Comment by warren-bank** [comment]
I'm sure there are many similar programs.. some better than others.
Doing a super quick search.. [this one](https://github.com/alpkeskin/rota) looks good.
Written in golang with binary releases, and it seems to support all popular protocols.

**Comment by Brijendrasial** [comment]
thanks warren for guiding in right direction. Its working awesome
