### ISSUE TITLE
Getting Http error 500 after hosting in render

### ISSUE THREAD

**Issue by NivinCNC** [warren-bank/HLS-Proxy#58]
I was abe to proxy a hls link in localhost but getting a 500 error while trying to proxy the same using deployed link on render

My link construction: 

```
  const proxy_url = 'https://cncstreamer.onrender.com:443'
  const referer_url = videoInfo?.referer
  const video_url = videoInfo?.server
  const file_extension = '.m3u8'
  const hls_proxy_url = `${proxy_url}/${btoa(`${video_url}|${referer_url}`)}${file_extension}`
```

Formulated Link : https://cncstreamer.onrender.com/aHR0cHM6Ly9qNW05d2FrY3B6LmNkbi1jZW50YXVydXMuY29tL2hsczIvMDEvMDcwOTIveWl2eXZkem50NWNnX24vbWFzdGVyLm0zdTg/dD1pTUs2X3lkM1pmRWllZW9BaUw5TVd1dXlmTXhhUjhYT0FRaE9TWk93WmpVJnM9MTczNTI5MzMwMiZlPTEyOTYwMCZmPTM1NDYzOTEzJnNydj1vZ3J5NXh0aHFycGYmaT0wLjQmc3A9NTAwJnAxPW9ncnk1eHRocXJwZiZwMj1vZ3J5NXh0aHFycGYmYXNuPTEzNTg3NnxodHRwczovL2VtYmVkd2lzaC5jb20=.m3u8

Need help to solve this

Note: Currently using  free instance of render for deploying this

**Comment by warren-bank** [comment]
[here](https://github.com/warren-bank/render-web-services/tree/hls-proxy) is what I've successfully tested in the past..
the server instance that I created at the time is still working now.

**Comment by NivinCNC** [comment]
> [here](https://github.com/warren-bank/render-web-services/tree/hls-proxy) is what I've successfully tested in the past.. the server instance that I created at the time is still working now.

I kinda used the same approach to deploy in render. And below is my approach 
![image](https://github.com/user-attachments/assets/c10985e9-1ff1-4e2b-a731-605af5f41f9f)
I also tried as same as your approach still same. You could check this by trying to proxy https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876 this link using deployed web service   "Referer":"https://embedwish.com/"    "Origin":"https://embedwish.com"

**Comment by warren-bank** [comment]
`--port 443` is almost guaranteed to cause a problem..
not only is this a privileged port number (as are all ports below 1024)..
but `443` is used by the web server..
if you bind to any port that is neither privileged nor in use (ex: `8080`),
render is smart enough to detect the server and tunnel traffic from `443` to it.

just use my configs as an example..
it really does work.

**Comment by NivinCNC** [comment]
I initially tried using your configs by refering the same repo you mentioned above. it didnt work, for that sake i changed to port 443. initially it was 8080

**Comment by warren-bank** [comment]
let me know after you've changed it back to `8080`.. and I'll give your server a quick test

**Comment by NivinCNC** [comment]
> let me know after you've changed it back to `8080`.. and I'll give your server a quick test
![image](https://github.com/user-attachments/assets/500af7f6-90fc-458c-8ebf-d8a83ea15e17)

Done!

**Comment by warren-bank** [comment]
and.. it's working!

* [direct video URL](https://news.cgtn.com/resource/live/english/cgtn-news.m3u8)
* [direct video Referer](https://www.cgtn.com/tv)
* [proxied URL](https://cncstreamer.onrender.com:443/aHR0cHM6Ly9uZXdzLmNndG4uY29tL3Jlc291cmNlL2xpdmUvZW5nbGlzaC9jZ3RuLW5ld3MubTN1OHxodHRwczovL3d3dy5jZ3RuLmNvbS90dg==.m3u8)
  - 200
* [Clappr video player](https://warren-bank.github.io/crx-webcast-reloaded/external_website/4-clappr/index.html#/watch/aHR0cHM6Ly9jbmNzdHJlYW1lci5vbnJlbmRlci5jb20vYUhSMGNITTZMeTl1WlhkekxtTm5kRzR1WTI5dEwzSmxjMjkxY21ObEwyeHBkbVV2Wlc1bmJHbHphQzlqWjNSdUxXNWxkM011YlROMU9IeG9kSFJ3Y3pvdkwzZDNkeTVqWjNSdUxtTnZiUzkwZGc9PS5tM3U4) playing the proxied video stream

next, I'll test your video URLs..
before that, I just wanted to test it with an video source that I know is stable

**Comment by warren-bank** [comment]
ok, the issue is coming from your video server..

* [direct video URL](https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876)
* [direct video Referer](https://embedwish.com/)
* [proxied URL](http://cncstreamer.onrender.com:443/aHR0cHM6Ly9qNW05d2FrY3B6LmNkbi1jZW50YXVydXMuY29tL2hsczIvMDEvMDcwOTIveWl2eXZkem50NWNnX24vbWFzdGVyLm0zdTg/dD1LWmZPQmxSYnUydGNnMzNVWmJIVXJGbWd4NVh4ckV4NWhyZ3BjQ21meUdnJnM9MTczNTMyMTM0NSZlPTEyOTYwMCZmPTM1NDYzOTEzJnNydj1vZ3J5NXh0aHFycGYmaT0wLjQmc3A9NTAwJnAxPW9ncnk1eHRocXJwZiZwMj1vZ3J5NXh0aHFycGYmYXNuPTEzNTg3NnxodHRwczovL2VtYmVkd2lzaC5jb20v.m3u8)
  - 400 (Cloudflare)
  - response:
    ```text
      <html>
      <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
      <body>
      <center><h1>400 Bad Request</h1></center>
      <center>The plain HTTP request was sent to HTTPS port</center>
      <hr><center>cloudflare</center>
      </body>
      </html>
      <!-- a padding to disable MSIE and Chrome friendly error page -->
      <!-- a padding to disable MSIE and Chrome friendly error page -->
      <!-- a padding to disable MSIE and Chrome friendly error page -->
      <!-- a padding to disable MSIE and Chrome friendly error page -->
      <!-- a padding to disable MSIE and Chrome friendly error page -->
      <!-- a padding to disable MSIE and Chrome friendly error page -->
    ```

**Comment by NivinCNC** [comment]
Am i missing any headers ? 

![image](https://github.com/user-attachments/assets/cbfb604e-11fd-45dd-bed0-1c1cd334640c)

These are the headers that are sent by the host embedwish.com
And i extracted that hls link from [Here](https://embedwish.com/e/gopldkwh5n90.html)

**Comment by warren-bank** [comment]
at this point.. it has entirely to do with how you've configured both your video server.. and Cloudflare as an intermediary

test request:

```bash
video_url='https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876'
orgin_url='https://embedwish.com'

curl -I -H "Origin: ${orgin_url}" -H "Referer: ${orgin_url}/" "$video_url"
```

response:

```text
HTTP/1.1 403 Forbidden
Server: nginx
Date: Fri, 27 Dec 2024 18:45:56 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 146
Connection: keep-alive
```

**Comment by NivinCNC** [comment]
> ```shell
> video_url='https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876'
> orgin_url='https://embedwish.com'
> 
> curl -I -H "Origin: ${orgin_url}" -H "Referer: ${orgin_url}/" "$video_url"
> ```

Test Request

`curl -I -H "Origin: https://embedwish.com" -H "Referer: https://embedwish.com/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, br, zstd" -H "Accept-Language: en-US,en;q=0.9" -H "Connection: keep-alive" -H "sec-ch-ua: \"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"" -H "sec-ch-ua-mobile: ?0" -H "sec-ch-ua-platform: \"Windows\"" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: cross-site" "https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876"`


Response:

```
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 27 Dec 2024 18:56:22 GMT
Content-Type: application/vnd.apple.mpegurl
Last-Modified: Fri, 27 Dec 2024 18:56:22 GMT
Connection: keep-alive
Expires: Thu, 27 Mar 2025 16:19:22 GMT
Cache-Control: max-age=8640000
Cache-Control: public, no-transform
Access-Control-Allow-Origin: *
X-Cache-Status: HIT
Content-Encoding: gzip
```

The issuse is with the headers

**Comment by NivinCNC** [comment]
> > ```shell
> > video_url='https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876'
> > orgin_url='https://embedwish.com'
> > 
> > curl -I -H "Origin: ${orgin_url}" -H "Referer: ${orgin_url}/" "$video_url"
> > ```
> 
> Test Request
> 
> `curl -I -H "Origin: https://embedwish.com" -H "Referer: https://embedwish.com/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, br, zstd" -H "Accept-Language: en-US,en;q=0.9" -H "Connection: keep-alive" -H "sec-ch-ua: \"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"" -H "sec-ch-ua-mobile: ?0" -H "sec-ch-ua-platform: \"Windows\"" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: cross-site" "https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876"`
> 
> Response:
> 
> ```
> HTTP/1.1 200 OK
> Server: nginx
> Date: Fri, 27 Dec 2024 18:56:22 GMT
> Content-Type: application/vnd.apple.mpegurl
> Last-Modified: Fri, 27 Dec 2024 18:56:22 GMT
> Connection: keep-alive
> Expires: Thu, 27 Mar 2025 16:19:22 GMT
> Cache-Control: max-age=8640000
> Cache-Control: public, no-transform
> Access-Control-Allow-Origin: *
> X-Cache-Status: HIT
> Content-Encoding: gzip
> ```
> 
> The issuse is with the headers



Can you guide me to attach these headers in my proxy server ?

**Comment by warren-bank** [comment]
did you take the server offline? I wanted to test something, but I'm getting `500` responses now.

**Comment by NivinCNC** [comment]
> did you take the server offline? I wanted to test something, but I'm getting `500` responses now.

No its working fine

**Comment by warren-bank** [comment]
oh yeah, you're right.. sorry
when I retest the earlier proxied URL for the good video host, it's still working..
when I tried to proxy a video URL that I got off of [your website](https://embedwish.com/)..
[this URL](https://cncstreamer.onrender.com/aHR0cHM6Ly96MXFvdnlkdWFkdXUuY2RuLWNlbnRhdXJ1cy5jb20vaGxzMi8wMS8wNTYwNi9nb3BsZGt3aDVuOTBfbi9tYXN0ZXIubTN1OD90PW5xcXk1ZHhXMFFva3dHenlTQXduaFQ4Ym9KVE52Tm1qcm04aDhRUjdyN2cmcz0xNzM1MzI1OTE5JmU9MTI5NjAwJmY9MjgwMzQ3NTYmc3J2PXl2cnZkenpoZ2J6MyZpPTAuNCZzcD01MDAmcDE9eXZydmR6emhnYnozJnAyPXl2cnZkenpoZ2J6MyZhc249NjE2N3xodHRwczovL2VtYmVkd2lzaC5jb20vZS9nb3BsZGt3aDVuOTAuaHRtbA==.m3u8) always returns 500, but it must be the upstream server's response..
my bad

**Comment by NivinCNC** [comment]
> > > ```shell
> > > video_url='https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876'
> > > orgin_url='https://embedwish.com'
> > > 
> > > curl -I -H "Origin: ${orgin_url}" -H "Referer: ${orgin_url}/" "$video_url"
> > > ```
> > 
> > 
> > Test Request
> > `curl -I -H "Origin: https://embedwish.com" -H "Referer: https://embedwish.com/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, br, zstd" -H "Accept-Language: en-US,en;q=0.9" -H "Connection: keep-alive" -H "sec-ch-ua: \"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"" -H "sec-ch-ua-mobile: ?0" -H "sec-ch-ua-platform: \"Windows\"" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: cross-site" "https://j5m9wakcpz.cdn-centaurus.com/hls2/01/07092/yivyvdznt5cg_n/master.m3u8?t=KZfOBlRbu2tcg33UZbHUrFmgx5XxrEx5hrgpcCmfyGg&s=1735321345&e=129600&f=35463913&srv=ogry5xthqrpf&i=0.4&sp=500&p1=ogry5xthqrpf&p2=ogry5xthqrpf&asn=135876"`
> > Response:
> > ```
> > HTTP/1.1 200 OK
> > Server: nginx
> > Date: Fri, 27 Dec 2024 18:56:22 GMT
> > Content-Type: application/vnd.apple.mpegurl
> > Last-Modified: Fri, 27 Dec 2024 18:56:22 GMT
> > Connection: keep-alive
> > Expires: Thu, 27 Mar 2025 16:19:22 GMT
> > Cache-Control: max-age=8640000
> > Cache-Control: public, no-transform
> > Access-Control-Allow-Origin: *
> > X-Cache-Status: HIT
> > Content-Encoding: gzip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The issuse is with the headers
> 
> Can you guide me to attach these headers in my proxy server ?

Did you ckeck on this..

**Comment by warren-bank** [comment]
well.. my suggestion is to:

* trial and error each request header until you find the one that's required
* either add `--copy-req-headers` or `--header <name=value>` to the hlsd command-line
  - depending on whether you want to hard-code the header to always be present in all requests, or
  - require that the http client that talks to your hlsd server always include it in its requests..<br>so they get copied to the proxied request on a per-request basis

**Comment by NivinCNC** [comment]
> upstream server's response

I wanted to do by client side coud you give me examble

**Comment by NivinCNC** [comment]
> well.. my suggestion is to:
> 
> * trial and error each request header until you find the one that's required
> * either add `--copy-req-headers` or `--header <name=value>` to the hlsd command-line
>   
>   * depending on whether you want to hard-code the header to always be present in all requests, or
>   * require that the http client that talks to your hlds server always include it in its requests..so they get copied to the proxied request on a per-request basis

I wanted to do it from client side. Could you give me a example

**Comment by warren-bank** [comment]
I think i'm going to close out this issue.
The server is working properly.
The application development for whatever project you're working on is outside the scope of this repo.
Best of luck.
